/* 状态对象 */
export default {
  recommends: [],       //推荐列表
  changeRecommends: {}, //更换推荐列表
  classes: [],          //漫画分类
  rankSorts: [],        //排行榜排序方式
  comicInfo: {},        //漫画信息
  chapters: [],         //漫画章节列表
  collections: [],      //收藏漫画列表
  readHistories: [],    //阅读历史记录
  searchList: [],       //搜素漫画列表
  searchResult: {},     //搜素漫画结果
  sellWellComics: [],   //畅销漫画列表
  serialComics: [],     //连载漫画列表
  memberEndComics: [],  //会员区完结漫画列表
  memberComics: [],     //全部会员漫画列表
  setMeals: [],         //会员套餐列表
  rechargeList: [],     //金币充值列表
  buyHistory: {},       //购买历史列表
  comicContents: {},    //漫画内容
  endEasySell: [],      //完结人气畅销列表
  endComics: [],        //完结整本列表
  recentEnds: [],       //最新完结列表
  comicList: [],         //排行榜/分类列表
}
